const beds = [
  {
    name: "Ліжко Спарта / Sparta з підйомним механізмом",
    category: "Ліжка",
    availability: "В наявності",
    manufacturer: "Soft-line",
    size: "200x200 см",
    type: "Без узголов'я",
    price: 5000,
    discountPrice: 4500,
  },
  {
    name: "Ліжко Аргон з підйомним механізмом",
    category: "Ліжка",
    availability: "Під замовлення",
    manufacturer: "Venger",
    size: "180x200 см",
    type: "З узголів'ям",
    price: 6000,
  },
  {
    name: "Ліжко Престиж з підйомним механізмом",
    category: "Ліжка",
    availability: "В наявності",
    manufacturer: "Green Line",
    size: "200x210 см",
    type: "Двоярусні",
    price: 7000,
    discountPrice: 6300,
  },
  {
    name: "Диван Токіо-2",
    category: "Дивани",
    availability: "В наявності",
    manufacturer: "Legko",
    size: "200x200 см",
    type: "Розкладачки",
    price: 3500,
  },
  {
    name: "Матрац Largo SLIM / Ларго Слім",
    category: "Матраци",
    availability: "Під замовлення",
    manufacturer: "Novelty",
    size: "200x200 см",
    type: "Без узголов'я",
    price: 4500,
  },
  {
    name: "Матрац ARGENTUM AMALTEA / Аргентум Амалті",
    category: "Матраци",
    availability: "В наявності",
    manufacturer: "Estella",
    size: "160x200 см",
    type: "Шафи",
    price: 5500,
    discountPrice: 4950,
  },
  {
    name: "Диван Браво",
    category: "Дивани",
    availability: "Під замовлення",
    manufacturer: "MiroMark",
    size: "180x200 см",
    type: "Розкладачки",
    price: 4000,
  },
  {
    name: "Ліжко МК-5",
    category: "Ліжка",
    availability: "В наявності",
    manufacturer: "Арбор Древ",
    size: "160x190 см",
    type: "З узголів'ям",
    price: 5000,
  },
  {
    name: "Ліжко Стандарт",
    category: "Ліжка",
    availability: "В наявності",
    manufacturer: "Venger",
    size: "180x200 см",
    type: "Без узголов'я",
    price: 5500,
    discountPrice: 4950,
  },
  {
    name: "Ліжко Універсал",
    category: "Ліжка",
    availability: "Під замовлення",
    manufacturer: "Green Line",
    size: "200x200 см",
    type: "Двоярусні",
    price: 6000,
  },
  {
    name: "Диван Лаунж",
    category: "Дивани",
    availability: "В наявності",
    manufacturer: "Legko",
    size: "200x210 см",
    type: "Розкладачки",
    price: 3500,
  },
  {
    name: "Матрац Еліт",
    category: "Матраци",
    availability: "Під замовлення",
    manufacturer: "Novelty",
    size: "160x200 см",
    type: "Без узголов'я",
    price: 4800,
  },
  {
    name: "Матрац Комфорт",
    category: "Матраци",
    availability: "В наявності",
    manufacturer: "Estella",
    size: "200x190 см",
    type: "Шафи",
    price: 5000,
  },
  {
    name: "Ліжко Артек",
    category: "Ліжка",
    availability: "В наявності",
    manufacturer: "MiroMark",
    size: "140x200 см",
    type: "З узголів'ям",
    price: 5500,
    discountPrice: 4950,
  },
  {
    name: "Диван Люкс",
    category: "Дивани",
    availability: "Під замовлення",
    manufacturer: "Venger",
    size: "160x200 см",
    type: "Розкладачки",
    price: 4000,
  },
  {
    name: "Ліжко Релакс",
    category: "Ліжка",
    availability: "В наявності",
    manufacturer: "Soft-line",
    size: "180x200 см",
    type: "Без узголов'я",
    price: 5500,
  },
  {
    name: "Матрац Престиж",
    category: "Матраци",
    availability: "Під замовлення",
    manufacturer: "Green Line",
    size: "200x200 см",
    type: "Шафи",
    price: 6000,
    discountPrice: 5400,
  },
  {
    name: "Ліжко Експрес",
    category: "Ліжка",
    availability: "В наявності",
    manufacturer: "Legko",
    size: "160x200 см",
    type: "Двоярусні",
    price: 6000,
  },
  {
    name: "Диван Модерн",
    category: "Дивани",
    availability: "Під замовлення",
    manufacturer: "Estella",
    size: "180x190 см",
    type: "Розкладачки",
    price: 4200,
  },
  {
    name: "Матрац Стандарт",
    category: "Матраци",
    availability: "В наявності",
    manufacturer: "MiroMark",
    size: "160x190 см",
    type: "Без узголов'я",
    price: 4700,
  },
  {
    name: "Ліжко Ренессанс",
    category: "Ліжка",
    availability: "В наявності",
    manufacturer: "Venger",
    size: "140x200 см",
    type: "З узголів'ям",
    price: 5500,
    discountPrice: 4950,
  },
  {
    name: "Ліжко Соната",
    category: "Ліжка",
    availability: "Під замовлення",
    manufacturer: "Soft-line",
    size: "180x200 см",
    type: "Двоярусні",
    price: 7000,
  },
  {
    name: "Диван Мечта",
    category: "Дивани",
    availability: "В наявності",
    manufacturer: "Green Line",
    size: "200x200 см",
    type: "Розкладачки",
    price: 3800,
  },
  {
    name: "Матрац Оптима",
    category: "Матраци",
    availability: "В наявності",
    manufacturer: "Legko",
    size: "160x200 см",
    type: "Шафи",
    price: 5300,
  },
  {
    name: "Ліжко Річмонд",
    category: "Ліжка",
    availability: "Під замовлення",
    manufacturer: "MiroMark",
    size: "200x200 см",
    type: "Без узголов'я",
    price: 6000,
  },
  {
    name: "Диван Вікторія",
    category: "Дивани",
    availability: "В наявності",
    manufacturer: "Estella",
    size: "200x190 см",
    type: "Розкладачки",
    price: 4200,
  },
  {
    name: "Ліжко Шарм",
    category: "Ліжка",
    availability: "Під замовлення",
    manufacturer: "Venger",
    size: "160x200 см",
    type: "З узголів'ям",
    price: 6500,
  },
  {
    name: "Матрац Флекс",
    category: "Матраци",
    availability: "В наявності",
    manufacturer: "Soft-line",
    size: "140x200 см",
    type: "Без узголов'я",
    price: 4800,
  },
  {
    name: "Ліжко Престиж 2",
    category: "Ліжка",
    availability: "В наявності",
    manufacturer: "Green Line",
    size: "180x200 см",
    type: "Двоярусні",
    price: 6000,
  },
  {
    name: "Диван Шик",
    category: "Дивани",
    availability: "Під замовлення",
    manufacturer: "MiroMark",
    size: "160x200 см",
    type: "Розкладачки",
    price: 4000,
  },
  {
    name: "Ліжко Класик",
    category: "Ліжка",
    availability: "В наявності",
    manufacturer: "Legko",
    size: "200x200 см",
    type: "Без узголов'я",
    price: 5500,
  },
  {
    name: "Матрац Солекс",
    category: "Матраци",
    availability: "Під замовлення",
    manufacturer: "Estella",
    size: "180x200 см",
    type: "Шафи",
    price: 5900,
  },
  {
    name: "Ліжко Альянс",
    category: "Ліжка",
    availability: "В наявності",
    manufacturer: "Venger",
    size: "160x190 см",
    type: "З узголів'ям",
    price: 5700,
    discountPrice: 5100,
  },
  {
    name: "Диван Оскар",
    category: "Дивани",
    availability: "В наявності",
    manufacturer: "Novelty",
    size: "180x190 см",
    type: "Розкладачки",
    price: 4300,
  },
  {
    name: "Ліжко Лаура",
    category: "Ліжка",
    availability: "Під замовлення",
    manufacturer: "Soft-line",
    size: "140x200 см",
    type: "Без узголов'я",
    price: 4900,
  },
  {
    name: "Матрац Ортопед",
    category: "Матраци",
    availability: "В наявності",
    manufacturer: "MiroMark",
    size: "160x200 см",
    type: "Шафи",
    price: 5200,
  },
  {
    name: "Диван Олімп",
    category: "Дивани",
    availability: "Під замовлення",
    manufacturer: "Venger",
    size: "200x200 см",
    type: "Розкладачки",
    price: 4300,
  },
  {
    name: "Ліжко Сіті",
    category: "Ліжка",
    availability: "В наявності",
    manufacturer: "Estella",
    size: "180x200 см",
    type: "З узголів'ям",
    price: 6000,
  },
  {
    name: "Матрац Комфорт 2",
    category: "Матраци",
    availability: "Під замовлення",
    manufacturer: "Green Line",
    size: "200x200 см",
    type: "Шафи",
    price: 5500,
  },
  {
    name: "Ліжко Інтер",
    category: "Ліжка",
    availability: "В наявності",
    manufacturer: "Soft-line",
    size: "160x190 см",
    type: "Двоярусні",
    price: 5000,
  },
]
let count = 0
for (let i = 0; i < beds.length; i++) {
  if (count === 8) count = 0
  beds[i].src = ` ./images/popular/img-${count}.png`
  count++
}
